// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL = "https://cghayvcmedqsxyqmsfiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnaGF5dmNtZWRxc3h5cW1zZml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTA4NDksImV4cCI6MjA3Mzc4Njg0OX0.9uxiHwPwneOkUpq8ljONoaTAKtAD0X6xKh2ZEubOs2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});